
const MESSAGE = {
	'CREATE_GAME': 'CREATE_GAME',
	'JOIN_GAME': 'JOIN_GAME',
	'LEAVE_GAME': 'LEAVE_GAME',
	'USER_JOINED': 'USER_JOINED',
	'USER_LEFT': 'USER_LEFT',
	'START_GAME': 'START_GAME',
	'NEW_TURN': 'NEW_TURN',
};

module.exports = {MESSAGE};